# Generated by Django 4.2.21 on 2025-12-05 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("proyectos", "0001_initial"),
        ("proveedores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Taller",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=200, verbose_name="Nombre del taller"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            (
                                "GESTION_RIESGOS",
                                "Gestión de Riesgos y Manejo de Crisis",
                            ),
                            ("TRANSFORMACION_DIGITAL", "Transformación Digital"),
                            ("MEJORA_CONTINUA", "Mejora Continua"),
                            ("SOSTENIBILIDAD", "Sostenibilidad Empresarial"),
                            ("OTRO", "Otro"),
                        ],
                        default="OTRO",
                        max_length=25,
                        verbose_name="Tipo",
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "contenido_programatico",
                    models.TextField(blank=True, verbose_name="Contenido programático"),
                ),
                ("objetivos", models.TextField(blank=True, verbose_name="Objetivos")),
                (
                    "duracion_horas",
                    models.DecimalField(
                        decimal_places=1,
                        default=4,
                        max_digits=4,
                        verbose_name="Duración (horas)",
                    ),
                ),
                (
                    "modalidad",
                    models.CharField(
                        choices=[
                            ("PRESENCIAL", "Presencial"),
                            ("VIRTUAL", "Virtual"),
                            ("HIBRIDO", "Híbrido"),
                        ],
                        default="PRESENCIAL",
                        max_length=15,
                        verbose_name="Modalidad",
                    ),
                ),
                (
                    "capacidad_maxima",
                    models.PositiveIntegerField(
                        default=40, verbose_name="Capacidad máxima"
                    ),
                ),
                (
                    "material_didactico",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="talleres/materiales/",
                        verbose_name="Material didáctico",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "facilitador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="talleres_facilitados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Facilitador",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="talleres",
                        to="proyectos.proyecto",
                        verbose_name="Proyecto asociado",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Taller",
                "verbose_name_plural": "Talleres",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SesionTaller",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha")),
                ("hora_inicio", models.TimeField(verbose_name="Hora de inicio")),
                ("hora_fin", models.TimeField(verbose_name="Hora de fin")),
                ("lugar", models.CharField(max_length=300, verbose_name="Lugar/Link")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PROGRAMADA", "Programada"),
                            ("EN_CURSO", "En curso"),
                            ("FINALIZADA", "Finalizada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PROGRAMADA",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "grabacion_url",
                    models.URLField(blank=True, verbose_name="URL de grabación"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "taller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sesiones",
                        to="talleres.taller",
                        verbose_name="Taller",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sesión de Taller",
                "verbose_name_plural": "Sesiones de Talleres",
                "ordering": ["-fecha", "-hora_inicio"],
            },
        ),
        migrations.CreateModel(
            name="InscripcionTaller",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "participante_nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del participante"
                    ),
                ),
                (
                    "participante_email",
                    models.EmailField(max_length=254, verbose_name="Email"),
                ),
                (
                    "participante_cargo",
                    models.CharField(blank=True, max_length=100, verbose_name="Cargo"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("INSCRITO", "Inscrito"),
                            ("CONFIRMADO", "Confirmado"),
                            ("ASISTIO", "Asistió"),
                            ("NO_ASISTIO", "No asistió"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="INSCRITO",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                ("fecha_inscripcion", models.DateTimeField(auto_now_add=True)),
                (
                    "confirmacion_enviada",
                    models.BooleanField(
                        default=False, verbose_name="Confirmación enviada"
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscripciones_talleres",
                        to="proveedores.proveedor",
                    ),
                ),
                (
                    "sesion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscripciones",
                        to="talleres.sesiontaller",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscripción",
                "verbose_name_plural": "Inscripciones",
                "unique_together": {("sesion", "participante_email")},
            },
        ),
        migrations.CreateModel(
            name="EvaluacionTaller",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "calificacion_general",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        verbose_name="Calificación general",
                    ),
                ),
                (
                    "calificacion_facilitador",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        verbose_name="Facilitador",
                    ),
                ),
                (
                    "calificacion_contenido",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        verbose_name="Contenido",
                    ),
                ),
                (
                    "calificacion_logistica",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        verbose_name="Logística",
                    ),
                ),
                (
                    "comentarios",
                    models.TextField(blank=True, verbose_name="Comentarios"),
                ),
                (
                    "sugerencias",
                    models.TextField(blank=True, verbose_name="Sugerencias"),
                ),
                ("fecha_evaluacion", models.DateTimeField(auto_now_add=True)),
                (
                    "inscripcion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluacion",
                        to="talleres.inscripciontaller",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluación de Taller",
                "verbose_name_plural": "Evaluaciones de Talleres",
            },
        ),
        migrations.CreateModel(
            name="CertificadoTaller",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "codigo_certificado",
                    models.CharField(max_length=50, unique=True, verbose_name="Código"),
                ),
                (
                    "fecha_emision",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de emisión"
                    ),
                ),
                (
                    "archivo_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="talleres/certificados/",
                        verbose_name="PDF",
                    ),
                ),
                ("enviado", models.BooleanField(default=False, verbose_name="Enviado")),
                (
                    "fecha_envio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de envío"
                    ),
                ),
                (
                    "inscripcion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificado",
                        to="talleres.inscripciontaller",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificado",
                "verbose_name_plural": "Certificados",
            },
        ),
        migrations.CreateModel(
            name="AsistenciaTaller",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hora_entrada",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora de entrada"
                    ),
                ),
                (
                    "hora_salida",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora de salida"
                    ),
                ),
                ("asistio", models.BooleanField(default=False, verbose_name="Asistió")),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "inscripcion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asistencia",
                        to="talleres.inscripciontaller",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asistencia",
                "verbose_name_plural": "Asistencias",
            },
        ),
    ]
