# Generated by Django 4.2.21 on 2025-12-05 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("empresas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantillaNotificacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "evento",
                    models.CharField(
                        choices=[
                            ("BIENVENIDA", "Bienvenida al Sistema"),
                            ("NUEVO_PROYECTO", "Asignación a Proyecto"),
                            ("CAMBIO_ETAPA", "Cambio de Etapa"),
                            ("TAREA_ASIGNADA", "Tarea Asignada"),
                            ("TAREA_VENCIDA", "Tarea Vencida"),
                            ("SESION_PROGRAMADA", "Sesión Programada"),
                            ("TALLER_INSCRIPCION", "Inscripción a Taller"),
                            ("TALLER_RECORDATORIO", "Recordatorio de Taller"),
                            ("CERTIFICADO_DISPONIBLE", "Certificado Disponible"),
                            ("REPORTE_GENERADO", "Reporte Generado"),
                            ("ALERTA_KPI", "Alerta de KPI"),
                            ("PROYECTO_FINALIZADO", "Proyecto Finalizado"),
                        ],
                        max_length=30,
                        verbose_name="Evento",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Correo Electrónico"),
                            ("WHATSAPP", "WhatsApp"),
                            ("SISTEMA", "Notificación del Sistema"),
                        ],
                        max_length=15,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "asunto",
                    models.CharField(blank=True, max_length=255, verbose_name="Asunto"),
                ),
                ("contenido", models.TextField(verbose_name="Contenido")),
                (
                    "contenido_html",
                    models.TextField(blank=True, verbose_name="Contenido HTML"),
                ),
                (
                    "variables_disponibles",
                    models.JSONField(
                        default=list, verbose_name="Variables Disponibles"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Plantilla de Notificación",
                "verbose_name_plural": "Plantillas de Notificaciones",
                "unique_together": {("evento", "tipo")},
            },
        ),
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Correo Electrónico"),
                            ("WHATSAPP", "WhatsApp"),
                            ("SISTEMA", "Notificación del Sistema"),
                        ],
                        max_length=15,
                        verbose_name="Tipo",
                    ),
                ),
                ("titulo", models.CharField(max_length=255, verbose_name="Título")),
                ("mensaje", models.TextField(verbose_name="Mensaje")),
                (
                    "datos",
                    models.JSONField(default=dict, verbose_name="Datos Adicionales"),
                ),
                ("enlace", models.URLField(blank=True, verbose_name="Enlace")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("ENVIADA", "Enviada"),
                            ("LEIDA", "Leída"),
                            ("FALLIDA", "Fallida"),
                        ],
                        default="PENDIENTE",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_programada",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Programada"
                    ),
                ),
                (
                    "fecha_envio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Envío"
                    ),
                ),
                (
                    "fecha_lectura",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Lectura"
                    ),
                ),
                (
                    "intentos",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Intentos"
                    ),
                ),
                (
                    "error_mensaje",
                    models.TextField(blank=True, verbose_name="Mensaje de Error"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plantilla",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="notificaciones.plantillanotificacion",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistorialEnvio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("WHATSAPP", "WhatsApp"),
                            ("SISTEMA", "Sistema"),
                        ],
                        max_length=15,
                        verbose_name="Canal",
                    ),
                ),
                (
                    "destinatario",
                    models.CharField(max_length=255, verbose_name="Destinatario"),
                ),
                ("exitoso", models.BooleanField(default=False, verbose_name="Exitoso")),
                (
                    "respuesta_servidor",
                    models.TextField(blank=True, verbose_name="Respuesta del Servidor"),
                ),
                (
                    "mensaje_id_externo",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ID Mensaje Externo"
                    ),
                ),
                ("fecha_envio", models.DateTimeField(auto_now_add=True)),
                (
                    "notificacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_envios",
                        to="notificaciones.notificacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Envío",
                "verbose_name_plural": "Historial de Envíos",
                "ordering": ["-fecha_envio"],
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionWhatsApp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        default="Principal", max_length=100, verbose_name="Nombre"
                    ),
                ),
                (
                    "numero_telefono",
                    models.CharField(max_length=20, verbose_name="Número de Teléfono"),
                ),
                ("api_url", models.URLField(verbose_name="URL de API")),
                ("api_key", models.CharField(max_length=255, verbose_name="API Key")),
                (
                    "webhook_secret",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Webhook Secret"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa_ancla",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_whatsapp",
                        to="empresas.empresaancla",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de WhatsApp",
                "verbose_name_plural": "Configuraciones de WhatsApp",
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionNotificacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email_activo",
                    models.BooleanField(default=True, verbose_name="Recibir por Email"),
                ),
                (
                    "whatsapp_activo",
                    models.BooleanField(
                        default=False, verbose_name="Recibir por WhatsApp"
                    ),
                ),
                (
                    "sistema_activo",
                    models.BooleanField(
                        default=True, verbose_name="Notificaciones del Sistema"
                    ),
                ),
                (
                    "notificar_tareas",
                    models.BooleanField(default=True, verbose_name="Notificar Tareas"),
                ),
                (
                    "notificar_sesiones",
                    models.BooleanField(
                        default=True, verbose_name="Notificar Sesiones"
                    ),
                ),
                (
                    "notificar_talleres",
                    models.BooleanField(
                        default=True, verbose_name="Notificar Talleres"
                    ),
                ),
                (
                    "notificar_reportes",
                    models.BooleanField(
                        default=True, verbose_name="Notificar Reportes"
                    ),
                ),
                (
                    "notificar_alertas",
                    models.BooleanField(default=True, verbose_name="Notificar Alertas"),
                ),
                (
                    "horario_no_molestar_inicio",
                    models.TimeField(
                        blank=True, null=True, verbose_name="No Molestar Desde"
                    ),
                ),
                (
                    "horario_no_molestar_fin",
                    models.TimeField(
                        blank=True, null=True, verbose_name="No Molestar Hasta"
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_notificaciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Notificación",
                "verbose_name_plural": "Configuraciones de Notificaciones",
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionEmail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        default="Principal", max_length=100, verbose_name="Nombre"
                    ),
                ),
                (
                    "email_remitente",
                    models.EmailField(max_length=254, verbose_name="Email Remitente"),
                ),
                (
                    "nombre_remitente",
                    models.CharField(max_length=100, verbose_name="Nombre Remitente"),
                ),
                (
                    "servidor_smtp",
                    models.CharField(
                        default="smtp.gmail.com",
                        max_length=255,
                        verbose_name="Servidor SMTP",
                    ),
                ),
                (
                    "puerto_smtp",
                    models.PositiveIntegerField(
                        default=587, verbose_name="Puerto SMTP"
                    ),
                ),
                (
                    "usar_tls",
                    models.BooleanField(default=True, verbose_name="Usar TLS"),
                ),
                (
                    "credenciales",
                    models.JSONField(default=dict, verbose_name="Credenciales"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa_ancla",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_email",
                        to="empresas.empresaancla",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Email",
                "verbose_name_plural": "Configuraciones de Email",
            },
        ),
        migrations.CreateModel(
            name="ColaNotificacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "prioridad",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Baja"),
                            (2, "Normal"),
                            (3, "Alta"),
                            (4, "Urgente"),
                        ],
                        default=2,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "procesado",
                    models.BooleanField(default=False, verbose_name="Procesado"),
                ),
                (
                    "fecha_procesamiento",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Procesamiento"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notificacion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cola",
                        to="notificaciones.notificacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cola de Notificación",
                "verbose_name_plural": "Cola de Notificaciones",
                "ordering": ["-prioridad", "created_at"],
            },
        ),
    ]
