# Generated by Django 4.2.21 on 2025-12-05 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("proveedores", "0001_initial"),
        ("empresas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del proyecto"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de inicio")),
                (
                    "fecha_fin_planeada",
                    models.DateField(verbose_name="Fecha fin planeada"),
                ),
                (
                    "fecha_fin_real",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha fin real"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PLANEACION", "En Planeación"),
                            ("EN_CURSO", "En Curso"),
                            ("FINALIZADO", "Finalizado"),
                            ("CANCELADO", "Cancelado"),
                            ("SUSPENDIDO", "Suspendido"),
                        ],
                        default="PLANEACION",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "presupuesto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Presupuesto (COP)",
                    ),
                ),
                (
                    "costo_por_proveedor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Costo por proveedor (COP)",
                    ),
                ),
                (
                    "numero_proveedores_planeado",
                    models.PositiveIntegerField(
                        default=40, verbose_name="Número de proveedores planeado"
                    ),
                ),
                (
                    "duracion_meses",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Duración (meses)"
                    ),
                ),
                (
                    "horas_por_proveedor",
                    models.PositiveIntegerField(
                        default=50, verbose_name="Horas por proveedor"
                    ),
                ),
                (
                    "objetivos",
                    models.TextField(blank=True, verbose_name="Objetivos del proyecto"),
                ),
                ("alcance", models.TextField(blank=True, verbose_name="Alcance")),
                ("notas", models.TextField(blank=True, verbose_name="Notas internas")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "director_proyecto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proyectos_dirigidos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Director del proyecto",
                    ),
                ),
                (
                    "empresa_ancla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proyectos",
                        to="empresas.empresaancla",
                        verbose_name="Empresa Ancla",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proyecto",
                "verbose_name_plural": "Proyectos",
                "ordering": ["-fecha_inicio", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="DocumentoProyecto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PROPUESTA", "Propuesta"),
                            ("CONTRATO", "Contrato"),
                            ("INFORME", "Informe"),
                            ("PRESENTACION", "Presentación"),
                            ("ACTA", "Acta"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=15,
                        verbose_name="Tipo de documento",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "archivo",
                    models.FileField(
                        upload_to="proyectos/documentos/", verbose_name="Archivo"
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0", max_length=20, verbose_name="Versión"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Subido"),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="proyectos.proyecto",
                        verbose_name="Proyecto",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Subido por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento del Proyecto",
                "verbose_name_plural": "Documentos del Proyecto",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ProveedorProyecto",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "etapa_actual",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Etapa 1: Diagnóstico"),
                            (2, "Etapa 2: Plan"),
                            (3, "Etapa 3: Implementación"),
                            (4, "Etapa 4: Monitoreo"),
                        ],
                        default=1,
                        verbose_name="Etapa actual",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente de iniciar"),
                            ("EN_PROCESO", "En proceso"),
                            ("COMPLETADO", "Completado"),
                            ("SUSPENDIDO", "Suspendido"),
                            ("RETIRADO", "Retirado"),
                        ],
                        default="PENDIENTE",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de inicio"
                    ),
                ),
                (
                    "fecha_fin_planeada",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha fin planeada"
                    ),
                ),
                (
                    "fecha_fin_real",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha fin real"
                    ),
                ),
                (
                    "porcentaje_avance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Porcentaje de avance",
                    ),
                ),
                (
                    "horas_consumidas",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="Horas consumidas",
                    ),
                ),
                (
                    "horas_planeadas",
                    models.DecimalField(
                        decimal_places=2,
                        default=50,
                        max_digits=6,
                        verbose_name="Horas planeadas",
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "motivo_suspension",
                    models.TextField(
                        blank=True, verbose_name="Motivo de suspensión/retiro"
                    ),
                ),
                (
                    "consultor_asignado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proveedores_asignados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Consultor asignado",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participaciones",
                        to="proveedores.proveedor",
                        verbose_name="Proveedor",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proveedores",
                        to="proyectos.proyecto",
                        verbose_name="Proyecto",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participación de Proveedor",
                "verbose_name_plural": "Participaciones de Proveedores",
                "ordering": ["proyecto", "proveedor"],
                "unique_together": {("proveedor", "proyecto")},
            },
        ),
    ]
