# Generated by Django 4.2.21 on 2025-12-05 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmpresaAncla",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre de la empresa"
                    ),
                ),
                (
                    "nit",
                    models.CharField(max_length=20, unique=True, verbose_name="NIT"),
                ),
                (
                    "razon_social",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Razón social"
                    ),
                ),
                ("direccion", models.TextField(blank=True, verbose_name="Dirección")),
                (
                    "ciudad",
                    models.CharField(blank=True, max_length=100, verbose_name="Ciudad"),
                ),
                (
                    "departamento",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Departamento"
                    ),
                ),
                (
                    "pais",
                    models.CharField(
                        default="Colombia", max_length=100, verbose_name="País"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email corporativo"
                    ),
                ),
                ("sitio_web", models.URLField(blank=True, verbose_name="Sitio web")),
                (
                    "sector_economico",
                    models.CharField(
                        choices=[
                            ("MANUFACTURA", "Manufactura"),
                            ("CONSTRUCCION", "Construcción"),
                            ("COMERCIO", "Comercio"),
                            ("SERVICIOS", "Servicios"),
                            ("TECNOLOGIA", "Tecnología"),
                            ("AGROINDUSTRIA", "Agroindustria"),
                            ("ENERGIA", "Energía y Minería"),
                            ("FINANCIERO", "Sector Financiero"),
                            ("SALUD", "Salud"),
                            ("EDUCACION", "Educación"),
                            ("TRANSPORTE", "Transporte y Logística"),
                            ("OTRO", "Otro"),
                        ],
                        default="OTRO",
                        max_length=20,
                        verbose_name="Sector económico",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "numero_empleados",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Número de empleados"
                    ),
                ),
                (
                    "anio_fundacion",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Año de fundación"
                    ),
                ),
                (
                    "contacto_nombre",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nombre del contacto"
                    ),
                ),
                (
                    "contacto_cargo",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Cargo del contacto"
                    ),
                ),
                (
                    "contacto_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email del contacto"
                    ),
                ),
                (
                    "contacto_telefono",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono del contacto"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="empresas/logos/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "configuracion",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Configuración"
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Notas internas")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empresa Ancla",
                "verbose_name_plural": "Empresas Ancla",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="UsuarioEmpresaAncla",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("ADMIN_EMPRESA", "Administrador"),
                            ("GESTOR", "Gestor"),
                            ("VISUALIZADOR", "Visualizador"),
                        ],
                        default="VISUALIZADOR",
                        max_length=20,
                        verbose_name="Rol en la empresa",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "empresa_ancla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuarios",
                        to="empresas.empresaancla",
                        verbose_name="Empresa Ancla",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empresas_ancla",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario de Empresa Ancla",
                "verbose_name_plural": "Usuarios de Empresas Ancla",
                "ordering": ["empresa_ancla", "usuario"],
                "unique_together": {("usuario", "empresa_ancla")},
            },
        ),
    ]
