# Generated by Django 4.2.21 on 2025-12-05 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("empresas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "razon_social",
                    models.CharField(max_length=250, verbose_name="Razón social"),
                ),
                (
                    "nit",
                    models.CharField(max_length=20, unique=True, verbose_name="NIT"),
                ),
                (
                    "nombre_comercial",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nombre comercial"
                    ),
                ),
                (
                    "representante_legal",
                    models.CharField(
                        max_length=200, verbose_name="Representante legal"
                    ),
                ),
                (
                    "cedula_representante",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Cédula del representante",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("telefono", models.CharField(max_length=20, verbose_name="Teléfono")),
                (
                    "celular",
                    models.CharField(blank=True, max_length=20, verbose_name="Celular"),
                ),
                ("direccion", models.TextField(verbose_name="Dirección")),
                ("ciudad", models.CharField(max_length=100, verbose_name="Ciudad")),
                (
                    "departamento",
                    models.CharField(max_length=100, verbose_name="Departamento"),
                ),
                (
                    "codigo_postal",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Código postal"
                    ),
                ),
                (
                    "sector_economico",
                    models.CharField(
                        choices=[
                            ("MANUFACTURA", "Manufactura"),
                            ("CONSTRUCCION", "Construcción"),
                            ("COMERCIO", "Comercio"),
                            ("SERVICIOS", "Servicios"),
                            ("TECNOLOGIA", "Tecnología"),
                            ("AGROINDUSTRIA", "Agroindustria"),
                            ("TRANSPORTE", "Transporte y Logística"),
                            ("OTRO", "Otro"),
                        ],
                        default="OTRO",
                        max_length=20,
                        verbose_name="Sector económico",
                    ),
                ),
                (
                    "actividad_economica",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Actividad económica"
                    ),
                ),
                (
                    "codigo_ciiu",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Código CIIU"
                    ),
                ),
                (
                    "tamano_empresa",
                    models.CharField(
                        choices=[
                            ("MICRO", "Microempresa (1-10 empleados)"),
                            ("PEQUENA", "Pequeña empresa (11-50 empleados)"),
                            ("MEDIANA", "Mediana empresa (51-200 empleados)"),
                            ("GRANDE", "Gran empresa (más de 200 empleados)"),
                        ],
                        default="MICRO",
                        max_length=10,
                        verbose_name="Tamaño de empresa",
                    ),
                ),
                (
                    "numero_empleados",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Número de empleados"
                    ),
                ),
                (
                    "anio_constitucion",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Año de constitución"
                    ),
                ),
                ("sitio_web", models.URLField(blank=True, verbose_name="Sitio web")),
                (
                    "ventas_anuales",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Ventas anuales (COP)",
                    ),
                ),
                (
                    "activos_totales",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Activos totales (COP)",
                    ),
                ),
                (
                    "contacto_nombre",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nombre del contacto"
                    ),
                ),
                (
                    "contacto_cargo",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Cargo del contacto"
                    ),
                ),
                (
                    "contacto_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email del contacto"
                    ),
                ),
                (
                    "contacto_telefono",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono del contacto"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="proveedores/logos/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "rut",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="proveedores/documentos/",
                        verbose_name="RUT",
                    ),
                ),
                (
                    "camara_comercio",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="proveedores/documentos/",
                        verbose_name="Cámara de Comercio",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True, verbose_name="Descripción de la empresa"
                    ),
                ),
                (
                    "productos_servicios",
                    models.TextField(
                        blank=True, verbose_name="Productos/Servicios que ofrece"
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Notas internas")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proveedor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario de acceso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
                "ordering": ["razon_social"],
            },
        ),
        migrations.CreateModel(
            name="DocumentoProveedor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("RUT", "RUT"),
                            ("CAMARA_COMERCIO", "Cámara de Comercio"),
                            ("ESTADOS_FINANCIEROS", "Estados Financieros"),
                            ("CERTIFICACION", "Certificación"),
                            ("POLIZA", "Póliza de Seguros"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de documento",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del documento"
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        upload_to="proveedores/documentos/", verbose_name="Archivo"
                    ),
                ),
                (
                    "fecha_emision",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de emisión"
                    ),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de vencimiento"
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Subido"),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="proveedores.proveedor",
                        verbose_name="Proveedor",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Subido por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento del Proveedor",
                "verbose_name_plural": "Documentos del Proveedor",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ProveedorEmpresaAncla",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fecha_vinculacion",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de vinculación"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo"),
                            ("INACTIVO", "Inactivo"),
                            ("SUSPENDIDO", "Suspendido"),
                        ],
                        default="ACTIVO",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Categoría"
                    ),
                ),
                (
                    "codigo_proveedor",
                    models.CharField(
                        blank=True,
                        help_text="Código interno del proveedor en la empresa ancla",
                        max_length=50,
                        verbose_name="Código de proveedor",
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "empresa_ancla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proveedores_vinculados",
                        to="empresas.empresaancla",
                        verbose_name="Empresa Ancla",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empresas_vinculadas",
                        to="proveedores.proveedor",
                        verbose_name="Proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vinculación Proveedor-Empresa",
                "verbose_name_plural": "Vinculaciones Proveedor-Empresa",
                "ordering": ["empresa_ancla", "proveedor"],
                "unique_together": {("proveedor", "empresa_ancla")},
            },
        ),
    ]
