# Generated by Django 4.2.21 on 2025-12-05 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("proyectos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccionMejora",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(verbose_name="Descripción de la acción"),
                ),
                (
                    "tipo_accion",
                    models.CharField(
                        choices=[
                            ("CORRECTIVA", "Correctiva"),
                            ("PREVENTIVA", "Preventiva"),
                            ("MEJORA", "Mejora"),
                        ],
                        default="MEJORA",
                        max_length=15,
                        verbose_name="Tipo de acción",
                    ),
                ),
                (
                    "recursos_necesarios",
                    models.TextField(blank=True, verbose_name="Recursos necesarios"),
                ),
                (
                    "responsable_sugerido",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Responsable sugerido"
                    ),
                ),
                (
                    "impacto_esperado",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=3,
                        help_text="1=Muy bajo, 5=Muy alto",
                        verbose_name="Impacto esperado",
                    ),
                ),
                (
                    "esfuerzo_requerido",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=3,
                        help_text="1=Muy bajo, 5=Muy alto",
                        verbose_name="Esfuerzo requerido",
                    ),
                ),
                (
                    "puntuacion_priorizacion",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Puntuación de priorización",
                    ),
                ),
                (
                    "seleccionada",
                    models.BooleanField(
                        default=False, verbose_name="Seleccionada para implementar"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Acción de Mejora",
                "verbose_name_plural": "Acciones de Mejora",
                "ordering": ["-puntuacion_priorizacion"],
            },
        ),
        migrations.CreateModel(
            name="CronogramaImplementacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "actividad",
                    models.CharField(max_length=200, verbose_name="Actividad"),
                ),
                (
                    "fecha_inicio_planeada",
                    models.DateField(verbose_name="Fecha inicio planeada"),
                ),
                (
                    "fecha_fin_planeada",
                    models.DateField(verbose_name="Fecha fin planeada"),
                ),
                (
                    "responsable",
                    models.CharField(max_length=200, verbose_name="Responsable"),
                ),
                ("recursos", models.TextField(blank=True, verbose_name="Recursos")),
                (
                    "entregable",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Entregable"
                    ),
                ),
                (
                    "orden",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Orden"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "accion_mejora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cronograma_items",
                        to="etapas.accionmejora",
                        verbose_name="Acción de mejora",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Cronograma",
                "verbose_name_plural": "Items de Cronograma",
                "ordering": ["orden", "fecha_inicio_planeada"],
            },
        ),
        migrations.CreateModel(
            name="Etapa1Diagnostico",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROCESO", "En proceso"),
                            ("COMPLETADO", "Completado"),
                        ],
                        default="PENDIENTE",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de inicio"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de finalización"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="etapas1_completadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Completado por",
                    ),
                ),
                (
                    "proveedor_proyecto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etapa1",
                        to="proyectos.proveedorproyecto",
                        verbose_name="Proveedor en Proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etapa 1 - Diagnóstico",
                "verbose_name_plural": "Etapas 1 - Diagnósticos",
            },
        ),
        migrations.CreateModel(
            name="Etapa2Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROCESO", "En proceso"),
                            ("EN_REVISION", "En revisión"),
                            ("APROBADO", "Aprobado"),
                            ("RECHAZADO", "Rechazado"),
                        ],
                        default="PENDIENTE",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de inicio"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de finalización"
                    ),
                ),
                (
                    "fecha_aprobacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de aprobación"
                    ),
                ),
                (
                    "observaciones_aprobacion",
                    models.TextField(
                        blank=True, verbose_name="Observaciones de aprobación"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "aprobado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planes_aprobados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprobado por",
                    ),
                ),
                (
                    "proveedor_proyecto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etapa2",
                        to="proyectos.proveedorproyecto",
                        verbose_name="Proveedor en Proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etapa 2 - Plan",
                "verbose_name_plural": "Etapas 2 - Planes",
            },
        ),
        migrations.CreateModel(
            name="Etapa3Implementacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROCESO", "En proceso"),
                            ("COMPLETADO", "Completado"),
                        ],
                        default="PENDIENTE",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de inicio"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de finalización"
                    ),
                ),
                (
                    "porcentaje_avance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Porcentaje de avance",
                    ),
                ),
                (
                    "horas_acompanamiento",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="Horas de acompañamiento",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "proveedor_proyecto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etapa3",
                        to="proyectos.proveedorproyecto",
                        verbose_name="Proveedor en Proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etapa 3 - Implementación",
                "verbose_name_plural": "Etapas 3 - Implementaciones",
            },
        ),
        migrations.CreateModel(
            name="Etapa4Monitoreo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROCESO", "En proceso"),
                            ("COMPLETADO", "Completado"),
                        ],
                        default="PENDIENTE",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de inicio"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de finalización"
                    ),
                ),
                (
                    "informe_final_generado",
                    models.BooleanField(
                        default=False, verbose_name="Informe final generado"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "proveedor_proyecto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etapa4",
                        to="proyectos.proveedorproyecto",
                        verbose_name="Proveedor en Proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etapa 4 - Monitoreo",
                "verbose_name_plural": "Etapas 4 - Monitoreos",
            },
        ),
        migrations.CreateModel(
            name="IndicadorKPI",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del indicador"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "valor_inicial",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Valor inicial",
                    ),
                ),
                (
                    "valor_actual",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Valor actual",
                    ),
                ),
                (
                    "valor_meta",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Valor meta",
                    ),
                ),
                (
                    "unidad_medida",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Unidad de medida"
                    ),
                ),
                (
                    "frecuencia_medicion",
                    models.CharField(
                        choices=[
                            ("SEMANAL", "Semanal"),
                            ("QUINCENAL", "Quincenal"),
                            ("MENSUAL", "Mensual"),
                        ],
                        default="SEMANAL",
                        max_length=15,
                        verbose_name="Frecuencia de medición",
                    ),
                ),
                (
                    "tendencia",
                    models.CharField(
                        choices=[
                            ("MEJORANDO", "Mejorando"),
                            ("ESTABLE", "Estable"),
                            ("EMPEORANDO", "Empeorando"),
                        ],
                        default="ESTABLE",
                        max_length=15,
                        verbose_name="Tendencia",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "etapa4",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicadores",
                        to="etapas.etapa4monitoreo",
                        verbose_name="Etapa 4",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indicador KPI",
                "verbose_name_plural": "Indicadores KPI",
            },
        ),
        migrations.CreateModel(
            name="VozCliente",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "empresa_ancla_contacto",
                    models.CharField(
                        max_length=200, verbose_name="Contacto de empresa ancla"
                    ),
                ),
                (
                    "cargo_contacto",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Cargo del contacto"
                    ),
                ),
                (
                    "fecha_entrevista",
                    models.DateField(verbose_name="Fecha de entrevista"),
                ),
                (
                    "necesidades_identificadas",
                    models.TextField(verbose_name="Necesidades identificadas"),
                ),
                ("expectativas", models.TextField(verbose_name="Expectativas")),
                (
                    "requerimientos_especificos",
                    models.TextField(
                        blank=True, verbose_name="Requerimientos específicos"
                    ),
                ),
                (
                    "fortalezas_proveedor",
                    models.TextField(
                        blank=True, verbose_name="Fortalezas del proveedor"
                    ),
                ),
                (
                    "areas_mejora",
                    models.TextField(
                        blank=True, verbose_name="Áreas de mejora identificadas"
                    ),
                ),
                (
                    "archivo_evidencia",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="etapas/voz_cliente/",
                        verbose_name="Archivo de evidencia",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "etapa1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voces_cliente",
                        to="etapas.etapa1diagnostico",
                        verbose_name="Etapa 1",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voz del Cliente",
                "verbose_name_plural": "Voces del Cliente",
                "ordering": ["-fecha_entrevista"],
            },
        ),
        migrations.CreateModel(
            name="TareaImplementacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROGRESO", "En progreso"),
                            ("COMPLETADA", "Completada"),
                            ("BLOQUEADA", "Bloqueada"),
                        ],
                        default="PENDIENTE",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("ALTA", "Alta"),
                            ("MEDIA", "Media"),
                            ("BAJA", "Baja"),
                        ],
                        default="MEDIA",
                        max_length=10,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "fecha_inicio_planeada",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha inicio planeada"
                    ),
                ),
                (
                    "fecha_fin_planeada",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha fin planeada"
                    ),
                ),
                (
                    "fecha_inicio_real",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha inicio real"
                    ),
                ),
                (
                    "fecha_fin_real",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha fin real"
                    ),
                ),
                (
                    "porcentaje_avance",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="% Avance"
                    ),
                ),
                (
                    "orden",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Orden"),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Notas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cronograma_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tareas",
                        to="etapas.cronogramaimplementacion",
                        verbose_name="Item de cronograma",
                    ),
                ),
                (
                    "etapa3",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tareas",
                        to="etapas.etapa3implementacion",
                        verbose_name="Etapa 3",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tareas_asignadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarea de Implementación",
                "verbose_name_plural": "Tareas de Implementación",
                "ordering": ["orden", "-prioridad", "fecha_fin_planeada"],
            },
        ),
        migrations.CreateModel(
            name="SesionAcompanamiento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fecha", models.DateTimeField(verbose_name="Fecha y hora")),
                (
                    "duracion_horas",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Duración (horas)"
                    ),
                ),
                (
                    "modalidad",
                    models.CharField(
                        choices=[("PRESENCIAL", "Presencial"), ("VIRTUAL", "Virtual")],
                        default="VIRTUAL",
                        max_length=15,
                        verbose_name="Modalidad",
                    ),
                ),
                ("temas_tratados", models.TextField(verbose_name="Temas tratados")),
                (
                    "compromisos",
                    models.TextField(blank=True, verbose_name="Compromisos"),
                ),
                (
                    "participantes",
                    models.TextField(blank=True, verbose_name="Participantes"),
                ),
                (
                    "archivo_acta",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="etapas/actas/",
                        verbose_name="Acta",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "consultor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sesiones_realizadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Consultor",
                    ),
                ),
                (
                    "etapa3",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sesiones",
                        to="etapas.etapa3implementacion",
                        verbose_name="Etapa 3",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sesión de Acompañamiento",
                "verbose_name_plural": "Sesiones de Acompañamiento",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="ObjetivoFortalecimiento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("objetivo", models.TextField(verbose_name="Objetivo")),
                (
                    "especifico",
                    models.TextField(
                        blank=True, verbose_name="Específico (qué se quiere lograr)"
                    ),
                ),
                (
                    "medible",
                    models.CharField(
                        max_length=200, verbose_name="Medible (indicador)"
                    ),
                ),
                (
                    "alcanzable",
                    models.TextField(
                        blank=True, verbose_name="Alcanzable (cómo se logrará)"
                    ),
                ),
                (
                    "relevante",
                    models.TextField(
                        blank=True, verbose_name="Relevante (por qué es importante)"
                    ),
                ),
                (
                    "temporal",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Temporal (plazo)"
                    ),
                ),
                (
                    "valor_inicial",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Valor inicial",
                    ),
                ),
                (
                    "valor_meta",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Valor meta",
                    ),
                ),
                (
                    "unidad_medida",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Unidad de medida"
                    ),
                ),
                (
                    "prioridad",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Prioridad"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "etapa1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objetivos",
                        to="etapas.etapa1diagnostico",
                        verbose_name="Etapa 1",
                    ),
                ),
            ],
            options={
                "verbose_name": "Objetivo de Fortalecimiento",
                "verbose_name_plural": "Objetivos de Fortalecimiento",
                "ordering": ["prioridad"],
            },
        ),
        migrations.CreateModel(
            name="MedicionKPI",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fecha_medicion", models.DateField(verbose_name="Fecha de medición")),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "indicador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mediciones",
                        to="etapas.indicadorkpi",
                        verbose_name="Indicador",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medición de KPI",
                "verbose_name_plural": "Mediciones de KPI",
                "ordering": ["-fecha_medicion"],
            },
        ),
        migrations.CreateModel(
            name="InformeCierre",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fecha_generacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de generación"
                    ),
                ),
                (
                    "resumen_ejecutivo",
                    models.TextField(verbose_name="Resumen ejecutivo"),
                ),
                (
                    "objetivos_logrados",
                    models.TextField(verbose_name="Objetivos logrados"),
                ),
                (
                    "mejoras_implementadas",
                    models.TextField(verbose_name="Mejoras implementadas"),
                ),
                (
                    "resultados_kpis",
                    models.JSONField(default=dict, verbose_name="Resultados de KPIs"),
                ),
                (
                    "lecciones_aprendidas",
                    models.TextField(blank=True, verbose_name="Lecciones aprendidas"),
                ),
                (
                    "recomendaciones",
                    models.TextField(blank=True, verbose_name="Recomendaciones"),
                ),
                (
                    "archivo_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="etapas/informes/",
                        verbose_name="PDF del informe",
                    ),
                ),
                (
                    "fecha_firma",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de firma"
                    ),
                ),
                (
                    "etapa4",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="informe_cierre",
                        to="etapas.etapa4monitoreo",
                        verbose_name="Etapa 4",
                    ),
                ),
                (
                    "firmado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="informes_firmados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Firmado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Informe de Cierre",
                "verbose_name_plural": "Informes de Cierre",
            },
        ),
        migrations.AddField(
            model_name="indicadorkpi",
            name="objetivo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kpis",
                to="etapas.objetivofortalecimiento",
                verbose_name="Objetivo asociado",
            ),
        ),
        migrations.CreateModel(
            name="HallazgoProblema",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "codigo",
                    models.CharField(blank=True, max_length=20, verbose_name="Código"),
                ),
                ("hallazgo", models.TextField(verbose_name="Hallazgo")),
                (
                    "problema_identificado",
                    models.TextField(verbose_name="Problema identificado"),
                ),
                ("causa_raiz", models.TextField(verbose_name="Causa raíz")),
                (
                    "area_impactada",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Área impactada"
                    ),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("ALTA", "Alta"),
                            ("MEDIA", "Media"),
                            ("BAJA", "Baja"),
                        ],
                        default="MEDIA",
                        max_length=10,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "orden",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Orden"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "etapa2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hallazgos",
                        to="etapas.etapa2plan",
                        verbose_name="Etapa 2",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hallazgo/Problema",
                "verbose_name_plural": "Hallazgos/Problemas",
                "ordering": ["orden", "-prioridad"],
            },
        ),
        migrations.CreateModel(
            name="EvidenciaImplementacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("DOCUMENTO", "Documento"),
                            ("IMAGEN", "Imagen"),
                            ("VIDEO", "Video"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=15,
                        verbose_name="Tipo",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "archivo",
                    models.FileField(
                        upload_to="etapas/evidencias/", verbose_name="Archivo"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tarea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidencias",
                        to="etapas.tareaimplementacion",
                        verbose_name="Tarea",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Subido por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evidencia",
                "verbose_name_plural": "Evidencias",
            },
        ),
        migrations.CreateModel(
            name="EvaluacionDirectiva",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha")),
                ("participantes", models.TextField(verbose_name="Participantes")),
                (
                    "objetivos_cumplidos",
                    models.TextField(verbose_name="Objetivos cumplidos"),
                ),
                (
                    "objetivos_pendientes",
                    models.TextField(blank=True, verbose_name="Objetivos pendientes"),
                ),
                (
                    "ajustes_requeridos",
                    models.TextField(blank=True, verbose_name="Ajustes requeridos"),
                ),
                (
                    "decisiones_tomadas",
                    models.TextField(blank=True, verbose_name="Decisiones tomadas"),
                ),
                (
                    "archivo_acta",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="etapas/evaluaciones/",
                        verbose_name="Acta",
                    ),
                ),
                (
                    "aprobado",
                    models.BooleanField(default=False, verbose_name="Aprobado"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "etapa4",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluaciones",
                        to="etapas.etapa4monitoreo",
                        verbose_name="Etapa 4",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluación Directiva",
                "verbose_name_plural": "Evaluaciones Directivas",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="DocumentoEtapa1",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("VOZ_CLIENTE", "Voz del Cliente"),
                            ("DIAGNOSTICO", "Diagnóstico"),
                            ("GRABACION", "Grabación"),
                            ("EVIDENCIA", "Evidencia"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=15,
                        verbose_name="Tipo",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "archivo",
                    models.FileField(
                        upload_to="etapas/etapa1/", verbose_name="Archivo"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "etapa1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="etapas.etapa1diagnostico",
                        verbose_name="Etapa 1",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Subido por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento Etapa 1",
                "verbose_name_plural": "Documentos Etapa 1",
            },
        ),
        migrations.AddField(
            model_name="cronogramaimplementacion",
            name="etapa2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cronograma",
                to="etapas.etapa2plan",
                verbose_name="Etapa 2",
            ),
        ),
        migrations.AddField(
            model_name="accionmejora",
            name="hallazgo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acciones",
                to="etapas.hallazgoproblema",
                verbose_name="Hallazgo",
            ),
        ),
        migrations.CreateModel(
            name="ReporteSemanal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "semana_numero",
                    models.PositiveSmallIntegerField(verbose_name="Número de semana"),
                ),
                (
                    "fecha_inicio_semana",
                    models.DateField(verbose_name="Inicio de semana"),
                ),
                ("fecha_fin_semana", models.DateField(verbose_name="Fin de semana")),
                ("resumen_avance", models.TextField(verbose_name="Resumen de avance")),
                (
                    "logros",
                    models.TextField(blank=True, verbose_name="Logros de la semana"),
                ),
                (
                    "dificultades",
                    models.TextField(
                        blank=True, verbose_name="Dificultades encontradas"
                    ),
                ),
                (
                    "proximas_acciones",
                    models.TextField(blank=True, verbose_name="Próximas acciones"),
                ),
                ("enviado", models.BooleanField(default=False, verbose_name="Enviado")),
                (
                    "fecha_envio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de envío"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "etapa4",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes_semanales",
                        to="etapas.etapa4monitoreo",
                        verbose_name="Etapa 4",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte Semanal",
                "verbose_name_plural": "Reportes Semanales",
                "ordering": ["-semana_numero"],
                "unique_together": {("etapa4", "semana_numero")},
            },
        ),
        migrations.CreateModel(
            name="DiagnosticoCompetitividad",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "area_evaluada",
                    models.CharField(
                        choices=[
                            ("ESTRATEGIA", "Estrategia y Dirección"),
                            ("COMERCIAL", "Gestión Comercial"),
                            ("OPERACIONES", "Operaciones y Producción"),
                            ("FINANCIERO", "Gestión Financiera"),
                            ("TALENTO", "Talento Humano"),
                            ("CALIDAD", "Gestión de Calidad"),
                            ("INNOVACION", "Innovación y Tecnología"),
                            ("SOSTENIBILIDAD", "Sostenibilidad"),
                        ],
                        max_length=20,
                        verbose_name="Área evaluada",
                    ),
                ),
                (
                    "nivel_madurez",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        help_text="1=Inicial, 2=Básico, 3=Definido, 4=Gestionado, 5=Optimizado",
                        verbose_name="Nivel de madurez",
                    ),
                ),
                (
                    "puntaje",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Puntaje",
                    ),
                ),
                ("fortalezas", models.TextField(blank=True, verbose_name="Fortalezas")),
                (
                    "debilidades",
                    models.TextField(blank=True, verbose_name="Debilidades"),
                ),
                (
                    "oportunidades",
                    models.TextField(blank=True, verbose_name="Oportunidades"),
                ),
                ("amenazas", models.TextField(blank=True, verbose_name="Amenazas")),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "etapa1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnosticos",
                        to="etapas.etapa1diagnostico",
                        verbose_name="Etapa 1",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diagnóstico de Competitividad",
                "verbose_name_plural": "Diagnósticos de Competitividad",
                "unique_together": {("etapa1", "area_evaluada")},
            },
        ),
    ]
