# Generated by Django 4.2.21 on 2025-12-05 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("empresas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantillaReporte",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "tipo_reporte",
                    models.CharField(
                        choices=[
                            ("AVANCE_PROVEEDOR", "Avance por Proveedor"),
                            ("CONSOLIDADO_PROYECTO", "Consolidado de Proyecto"),
                            ("EJECUTIVO", "Informe Ejecutivo"),
                            ("COMPARATIVO", "Comparativo"),
                            ("KPIS", "Reporte de KPIs"),
                        ],
                        max_length=25,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "archivo_plantilla",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="reportes/plantillas/",
                        verbose_name="Plantilla",
                    ),
                ),
                (
                    "configuracion",
                    models.JSONField(default=dict, verbose_name="Configuración"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Plantilla de Reporte",
                "verbose_name_plural": "Plantillas de Reportes",
            },
        ),
        migrations.CreateModel(
            name="ReporteGenerado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("AVANCE_PROVEEDOR", "Avance por Proveedor"),
                            ("CONSOLIDADO_PROYECTO", "Consolidado de Proyecto"),
                            ("EJECUTIVO", "Informe Ejecutivo"),
                            ("COMPARATIVO", "Comparativo"),
                            ("KPIS", "Reporte de KPIs"),
                        ],
                        max_length=25,
                        verbose_name="Tipo",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "parametros",
                    models.JSONField(default=dict, verbose_name="Parámetros"),
                ),
                (
                    "archivo",
                    models.FileField(upload_to="reportes/", verbose_name="Archivo"),
                ),
                (
                    "formato",
                    models.CharField(
                        default="PDF", max_length=10, verbose_name="Formato"
                    ),
                ),
                ("fecha_generacion", models.DateTimeField(auto_now_add=True)),
                (
                    "generado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reportes_generados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte Generado",
                "verbose_name_plural": "Reportes Generados",
                "ordering": ["-fecha_generacion"],
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionReporteAutomatico",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo_reporte",
                    models.CharField(
                        choices=[
                            ("AVANCE_PROVEEDOR", "Avance por Proveedor"),
                            ("CONSOLIDADO_PROYECTO", "Consolidado de Proyecto"),
                            ("EJECUTIVO", "Informe Ejecutivo"),
                            ("COMPARATIVO", "Comparativo"),
                            ("KPIS", "Reporte de KPIs"),
                        ],
                        max_length=25,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "frecuencia",
                    models.CharField(
                        choices=[
                            ("DIARIO", "Diario"),
                            ("SEMANAL", "Semanal"),
                            ("QUINCENAL", "Quincenal"),
                            ("MENSUAL", "Mensual"),
                        ],
                        max_length=15,
                        verbose_name="Frecuencia",
                    ),
                ),
                (
                    "destinatarios",
                    models.JSONField(default=list, verbose_name="Destinatarios"),
                ),
                (
                    "hora_envio",
                    models.TimeField(default="08:00", verbose_name="Hora de envío"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "empresa_ancla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuraciones_reporte",
                        to="empresas.empresaancla",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Reporte Automático",
                "verbose_name_plural": "Configuraciones de Reportes Automáticos",
            },
        ),
    ]
